package me.stevemmmmm.thepitremake.utils;

public class RomanUtils {
	
	public static RomanUtils INSTANCE;
	
	 public static RomanUtils getInstance() {
	        if (INSTANCE == null) INSTANCE = new RomanUtils();

	        return INSTANCE;
	    }

	 public String convertToRomanNumeral(int value) {
		    switch (value) {
		      case 0:
		        return "None";
		      case 1:
		        return "I";
		      case 2:
		        return "II";
		      case 3:
		        return "III";
		      case 4:
		        return "IV";
		      case 5:
		        return "V";
		      case 6:
		        return "VI";
		      case 7:
		        return "VII";
		      case 8:
		        return "VIII";
		      case 9:
		        return "IX";
		      case 10:
		        return "X";
		      case 11:
		        return "XI";
		      case 12:
		        return "XII";
		      case 13:
		        return "XIII";
		      case 14:
		        return "XIV";
		      case 15:
		        return "XV";
		      case 16:
		        return "XVI";
		      case 17:
		        return "XVII";
		      case 18:
		        return "XVIII";
		      case 19:
		        return "XIX";
		      case 20:
		        return "XX";
		      case 21:
		        return "XXI";
		      case 22:
		        return "XXII";
		      case 23:
		        return "XXIII";
		      case 24:
		        return "XXIV";
		      case 25:
		        return "XXV";
		      case 26:
		        return "XXVI";
		      case 27:
		        return "XXVII";
		      case 28:
		        return "XXVIII";
		      case 29:
		        return "XXIX";
		      case 30:
		        return "XXX";
		      case 31:
		          return "XXXI";
		      case 32:
		          return "XXXII";
		      case 33:
		          return "XXXIII";
		      case 34:
		          return "XXXIV";
		      case 35:
		          return "XXXV";
		      case 36:
		          return "XXXVI";
		      case 37:
		          return "XXXVII";
		      case 38:
		          return "XXXVIII";
		      case 39:
		          return "XXXIX";
		      case 40:
		          return "XL";
		      case 41:
		          return "XLI";
		      case 42:
		          return "XLII";		          
		      case 43:
		        return "XLIII";
		      case 44:
			        return "XLIV";
		      case 45:
			        return "XLV";
		      case 46:
			        return "XLVI";
		      case 47:
			        return "XLVII";
		      case 48:
			        return "XLVIII";
		      case 49:
			        return "XLIX";
		      case 50:
			        return "L";
		      case 51:
			        return "LI";
		      case 52:
			        return "LII";
		      case 53:
			        return "LIII";
		      case 54:
			        return "LIV";
		      case 55:
			        return "LV";
		      case 56:
			        return "LVI";
		      case 57:
			        return "LVII";
		      case 58:
			        return "LVIII";
		      case 59:
			        return "LIX";
		      case 60:
			        return "LX";
		      case 61:
			        return "LXI";
		      case 62:
			        return "LXII";
		      case 63:
			        return "LXIII";
		      case 64:
			        return "LXIV";
		      case 65:
			        return "LXV";
		      case 66:
			        return "LXVI";
		      case 67:
			        return "LXVII";
		      case 68:
			        return "LXVIII";
		      case 69:
			        return "LXIX";
		      case 70:
			        return "LXX";
		    } 
		    return null;
		  }
		  
		  public int convertRomanNumeralToInteger(String numeral) {
		    switch (numeral) {
		      case "I":
		        return 1;
		      case "II":
		        return 2;
		      case "III":
			    return 3;
		      case "IV":
			    return 4;
		      case "V":
			    return 5;
		      case "VI":
			    return 6;
		      case "VII":
			    return 7;
		      case "VIII":
			    return 8;
		      case "IX":
			    return 9;
		      case "X":
			    return 10;
		      case "XI":
			    return 11;
		      case "XII":
			    return 12;
		      case "XIII":
			    return 13;
		      case "XIV":
			    return 14;
		      case "XV":
			    return 15;
		      case "XVI":
			    return 16;
		      case "XVII":
			    return 17;
		      case "XVIII":
			    return 18;
		      case "XIX":
			    return 19;
		      case "XX":
			    return 20;
		      case "XXI":
			    return 21;
		      case "XXII":
			    return 22;
		      case "XXIII":
			    return 23;
		      case "XXIV":
			    return 24;
		      case "XXV":
			    return 25;
		      case "XXVI":
			    return 26;
		      case "XXVII":
			    return 27;
		      case "XXVIII":
			    return 28;
		      case "XXIX":
			    return 29;
		      case "XXX":
			    return 30;
		      case "XXXI":
			    return 31;
		      case "XXXII":
			    return 32;
		      case "XXXIII":
			    return 33;
		      case "XXXIV":
			    return 34;
		      case "XXXV":
			    return 35;
		      case "XXXVI":
				return 36;
		      case "XXXVII":
				return 37;    
		      case "XXXVIII":
				return 38;
		      case "XXXIX":
				return 39;
		      case "XL":
				return 40;
		      case "XLI":
				return 41;
		      case "XLII":
				return 42;
		      case "XLIII":
				return 43;
		      case "XLIV":
				return 44;
		      case "XLV":
				return 45;
		      case "XLVI":
				return 46;
		      case "XLVII":
				return 47;
		      case "XLVIII":
				return 48;
		      case "XLIX":
				return 49;
		      case "L":
		  		return 50;
		      case "LI":
		  		return 51;
		      case "LII":
		  		return 52;
		      case "LIII":
		  		return 53;
		      case "LIV":
		  		return 54;
		      case "LV":
		  		return 55;
		      case "LVI":
		  		return 56;
		      case "LVII":
		  		return 57;
		      case "LVIII":
		  		return 58;
		      case "LIX":
		  		return 59;
		      case "LX":
		  		return 60;
		      case "LXI":
		  		return 61;
		      case "LXII":
		  		return 62;
		      case "LXIII":
		  		return 63;
		      case "LXIV":
		  		return 64;
		      case "LXV":
		  		return 65;
		      case "LXVI":
		  		return 66;
		      case "LXVII":
		  		return 67;
		      case "LXVIII":
		  		return 68;
		      case "LXIX":
		  		return 69;
		      case "LXX":
		  		return 70;  	
		    } 
		    return -1;
		  }
}